// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	ImgURL      string  `json:"imgURL"`
	Sell        *Price  `json:"sell"`
	Buy         *Price  `json:"buy"`
	Description *string `json:"description"`
	Type        string  `json:"type"`
	Rarity      string  `json:"rarity"`
	Level       string  `json:"level"`
}

type ItemNamePair struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Price struct {
	Gold   string `json:"gold"`
	Silver string `json:"silver"`
	Copper string `json:"copper"`
}
